openapi: '3.0.0'
info:
  version: '1.0'
  title: NFT
servers:
  - url: https://api.affondra.com
tags:
  - name: NFT
  - name: Affondra
  - name: Faucet
paths:

  /nft/denoms:
    get:
      summary: Get list of Denoms.
      tags:
      - NFT
      operationId: /nft/denoms
      responses:
        200:
          description: 'Success'
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  height:
                    type: "integer"
                  result:
                    items:
                      type: "string"
                      example: ["denom1", "denom2"]

  /nft/owner/{address}:
    get:
      summary: Get list of NFTs a specified owner have.
      description: Get list of NFTs a specified owner have.
      tags:
        - NFT
      operationId: getNftsByOwner
      parameters:
      - name: "address"
        description: 'An owner address'
        in: "path"
        required: true
        schema:
          type: string
          example: cosmos1gzfwesw9h0yp6pjr32ku4f3f28usezzarrqegh
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  height:
                    type: "integer"
                  result:
                    type: "object"
                    properties:
                      type:
                        type: "string"
                        example: "cosmos-sdk/Owner"
                      value:
                        type: "object"
                        properties:
                          address:
                            type: "string"
                            example: "COSMOS_ADDRESS"
                          idCollections:
                            type: array
                            nullable: true
                            items:
                              type: "object"
                              properties:
                                denom:
                                  type: "string"
                                  example: "DENOM_NAME"
                                ids:
                                  type: "array"
                                  items:
                                    type: "string"
                                    example: ["aaa", "bbb"]
  /nft/owners/collection/{denom}:
    get:
      summary: Get list of NFTs a specified owner have in a specified denom.
      description: Get list of NFTs a specified owner have in a specified denom.
      tags:
        - NFT
      operationId: getNftsByOwnerAndDenom
      parameters:
      - in: "path"
        name: "denom"
        description: 'A NFT denom'
        required: true
        schema:
          type: string
          example: crypto-kitties
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
  /nft/collection/{denom}:
    get:
      summary: Get list of NFTs in a specified denom.
      description: Get list of NFTs in a specified denom.
      tags:
        - NFT
      operationId: getNftsByDenom
      parameters:
      - in: "path"
        name: "denom"
        description: 'A NFT denom'
        required: true
        schema:
          type: string
          example: crypto-kitties
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
  /nft/supply/{denom}:
    get:
      summary: Return total amount of tokens in a specified denom.
      tags:
        - NFT
      operationId: getSupplyByDenom
      deprecated: false
      parameters:
        - in: path
          name: denom
          required: true
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
  /nfts/mint:
    post:
      summary: mint new NFT
      tags:
        - NFT
      operationId: /nfts/mint
      deprecated: false
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/nftsMintrequest'
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
  /nfts/transfer:
    post:
      summary: transfer NFT
      tags:
        - NFT
      operationId: /nfts/transfer
      deprecated: false
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                base_req:
                  $ref: '#/components/schemas/BaseReq'
                denom:
                  type: string
                id:
                  type: string
                recipient:
                  type: string
              required:
              - base_req
              - denom
              - id
              - recipient
            example:
              base_req:
                from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
                memo: "Sent from Postman \U0001F680"
                chain_id: voter
                account_number: 0
                sequence: 1
                gas: 200000
                gas_adjustment: 1.2
                fees:
                - denom: token
                  amount: 50
                simulate: false
              denom: MyToken
              id: aaa
              recipient: cosmos1atsc0j4w23derwmv98n72y28vdxsalp4zpcgz2
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
  /nfts/collection/{denom}/nft/{nftId}/metadata:
    put:
      summary: Update NFT metadata
      tags:
        - NFT
      operationId: /nfts/collection/crypto-kitties/nft/aaa/metadata
      deprecated: false
      parameters:
      - $ref: '#/components/parameters/denom'
      - $ref: '#/components/parameters/nftId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                base_req:
                  $ref: '#/components/schemas/BaseReq'
                denom:
                  type: string
                id:
                  type: string
                tokenURI:
                  type: string
              required:
              - base_req
              - denom
              - id
              - tokenURI
            example:
              base_req:
                from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
                memo: "Sent from Postman \U0001F680"
                chain_id: voter
                account_number: 0
                sequence: 1
                gas: 200000
                gas_adjustment: 1.2
                fees:
                - denom: token
                  amount: 50
                simulate: false
              denom: crypto-kitties
              id: aaa
              tokenURI: http://changeurl:8080
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
  /nfts/collection/{denom}/nft/{nftId}/burn:
    put:
      summary: Burn the NFT
      tags:
        - NFT
      operationId: Burn (delete) a specify NFT.
      parameters:
        - $ref: '#/components/parameters/denom'
        - $ref: '#/components/parameters/nftId'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                base_req:
                  $ref: '#/components/schemas/BaseReq'
                denom:
                  type: string
                id:
                  type: string
              required:
              - base_req
              - denom
              - id
            example:
              base_req:
                from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
                memo: "Sent from Postman \U0001F680"
                chain_id: voter
                account_number: 0
                sequence: 1
                gas: 200000
                gas_adjustment: 1.2
                fees:
                - denom: token
                  amount: 50
                simulate: false
              denom: crypto-kitties
              id: aaa
      responses:
        200:
          description: ''
          headers: {}

  /affondra/item:
    get:
      summary: Get list of items.
      tags:
      - Affondra
      operationId: /affondra/item
      responses:
        200:
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    post:
      summary: Sell item.
      tags:
      - Affondra
      operationId: /affondra/item
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/createItemRequest'
      responses:
        200:
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    put:
      summary: Update item info.
      tags:
      - Affondra
      operationId: /affondra/item
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/setItemRequest'
      responses:
        200:
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    delete:
      summary: Delete item info.
      tags:
      - Affondra
      operationId: /affondra/item
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/deleteItemRequest'
      responses:
        200:
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'


  /affondra/item/{id}:
    get:
      summary: Get a particular item.
      tags:
      - Affondra
      operationId: /affondra/item/owner
      parameters:
      - name: "id"
        description: 'item id (uuid)'
        in: "path"
        required: true
        schema:
          type: string
          example: 3af286d7-f61b-4525-b3b2-53e62c57babb
      responses:
        200:
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'

  /affondra/item/owner/{address}:
    get:
      summary: Get list of items of owner address.
      tags:
      - Affondra
      operationId: /affondra/item/owner
      parameters:
      - name: "address"
        description: 'An owner address'
        in: "path"
        required: true
        schema:
          type: string
          example: cosmos1gzfwesw9h0yp6pjr32ku4f3f28usezzarrqegh
      responses:
        200:
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'

  /affondra/item/denom/{denom}:
    get:
      summary: Get list of items of particular denom.
      tags:
      - Affondra
      operationId: /affondra/item/denom
      parameters:
      - in: "path"
        name: "denom"
        description: 'A NFT denom'
        required: true
        schema:
          type: string
          example: crypto-kitties
      responses:
        200:
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'


  /faucet/mint:
    post:
      summary: Get faucet
      tags:
      - Faucet
      operationId: /faucet/mint
      responses:
        200:
          description: 'Success'
          content:
            application/json:
              schema:
                type: "object"

  /affondra/buy:
    post:
      summary: Buy a item
      tags:
      - Affondra
      operationId: /affondra/item/buy
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/buyItemRequest'
      responses:
        200:
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'

components:
  parameters:
    denom:
      name: denom
      in: path
      description: A denom of NFT.
      required: true
      schema:
        type: string
        example: crypto-kitties
    nftId:
      name: nftId
      in: path
      description: A id of NFT.
      required: true
      schema:
        type: string
        example: aaa
  requestBodies:
    nftsMintrequest:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              base_req:
                $ref: '#/components/schemas/BaseReq'
              recipient:
                type: string
              denom:
                type: string
              id:
                type: string
              tokenURI:
                type: string
            required:
            - base_req
            - recipient
            - denom
            - id
            - tokenURI
          example:
            base_req:
              from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
              memo: "Sent from Postman \U0001F680"
              chain_id: voter
              account_number: 0
              sequence: 1
              gas: 200000
              gas_adjustment: 1.2
              fees:
              - denom: token
                amount: 50
              simulate: false
            recipient: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
            denom: MyToken
            id: aaa
            tokenURI: http://localhost:8080
    createItemRequest:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              base_req:
                $ref: '#/components/schemas/BaseReq'
              creator:
                type: string
              denom:
                type: string
              id:
                type: string
              price:
                type: string
              affiliate:
                type: string
              inSale:
                type: string
              description:
                type: string
            required:
            - base_req
            - creator
            - denom
            - id
            - price
            - affiliate
            - inSale
          example:
            base_req:
              from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
              memo: "Sent from Postman \U0001F680"
              chain_id: voter
            creator: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
            denom: MyToken
            id: aaa
            price: 100affondollar
            affiliate: 10affondollar
            inSale: true
            description: This item is awesome!
    setItemRequest:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              base_req:
                $ref: '#/components/schemas/BaseReq'
                id:
                type: string
              denom:
                type: string
              nftId:
                type: string
              price:
                type: string
              affiliate:
                type: string
              inSale:
                type: string
              description:
                type: string
            required:
            - base_req
            - id
            - creator
            - denom
            - nftId
            - price
            - affiliate
            - inSale
          example:
            base_req:
              from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
              memo: "Sent from Postman \U0001F680"
              chain_id: voter
            creator: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
            id:
            denom: MyToken
            nftId: 3af286d7-f61b-4525-b3b2-53e62c57babb
            price: 100affondollar
            affiliate: 10affondollar
            inSale: true
            description: This item is awesome!
    deleteItemRequest:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              base_req:
                $ref: '#/components/schemas/BaseReq'
                id:
                type: string
              creator:
                type: string
            required:
            - base_req
            - id
            - creator
          example:
            base_req:
              from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
              memo: "Sent from Postman \U0001F680"
              chain_id: voter
            creator: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
            id: aaa
    buyItemRequest:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              base_req:
                $ref: '#/components/schemas/BaseReq'
                id:
                type: string
              receiiver:
                type: string
              introduced_by:
                type: string
            required:
            - base_req
            - id
            - receiver
          example:
            base_req:
              from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
              memo: "Sent from Postman \U0001F680"
              chain_id: voter
            receiver: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
            id: aaa
  schemas:
    BaseReq:
      type: object
      properties:
        from:
          type: string
        chain_id:
          type: string
      required:
      - from
      - chain_id
      example:
        from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
        chain_id: affondra
    Coin:
      type: object
      properties:
        denom:
          type: string
        amount:
          type: integer
      example:
        denom: token
        amount: 50
    Item:
      type: object
      properties:
        creator:
          type: string
        id:
          type: string
        denom:
          type: string
        nftId:
          type: string
        price:
          $ref: '#/components/schemas/Coin'
        affiliate:
          $ref: '#/components/schemas/Coin'
        receiver:
          type: string
        description:
          type: string
        insale:
          type: boolean
      example:
        creator: cosmos10dhsus4sl07vu0mltw74jmseh64ayxg63mqhm9
        id: 3af286d7-f61b-4525-b3b2-53e62c57babb
        denom: crypto-kitties
        nftId: aaa
        price: {denom: token, amount: 1000}
        affiliate: {denom: token, amount: 1000}
        receiver:
        description: This item is awesome!
        insale: true
