swagger: '2.0'
info:
  version: '1.0'
  title: NFT
  contact: {}
host: localhost:1317
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /nft/denoms:
    get:
      summary: Get list of Denoms.
      tags:
      - Misc
      operationId: /nft/denoms
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: ''
          headers: {}
  /nft/owner/{address}:
    get:
      summary: Get list of NFTs a specified owner have.
      description: Get list of NFTs a specified owner have.
      tags:
      - Misc
      operationId: getNftsByOwner
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: ''
          headers: {}
  /nft/owners/collection/{denom}:
    get:
      summary: Get list of NFTs a specified owner have in a specified denom.
      description: Get list of NFTs a specified owner have in a specified denom.
      tags:
      - Misc
      operationId: getNftsByOwnerAndDenom
      responses:
        200:
          description: ''
          headers: {}
  /nft/collection/{denom}:
    get:
      summary: Get list of NFTs in a specified denom.
      description: Get list of NFTs in a specified denom.
      tags:
      - Misc
      operationId: getNftsByDenom
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: ''
          headers: {}
  /nft/supply/{denom}:
    get:
      summary: Return total amount of tokens in a specified denom.
      tags:
      - Misc
      operationId: getSupplyByDenom
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: ''
          headers: {}
  /nfts/mint:
    post:
      summary: /nfts/mint
      tags:
      - Misc
      operationId: /nfts/mint
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/~1nfts~1mintrequest'
      responses:
        200:
          description: ''
          headers: {}
  /nfts/transfer:
    post:
      summary: /nfts/transfer
      tags:
      - Misc
      operationId: /nfts/transfer
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/~1nfts~1transferrequest'
      responses:
        200:
          description: ''
          headers: {}
  /nfts/collection/crypto-kitties/nft/aaa/metadata:
    put:
      summary: /nfts/collection/crypto-kitties/nft/aaa/metadata
      tags:
      - Misc
      operationId: /nfts/collection/crypto-kitties/nft/aaa/metadata
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/~1nfts~1collection~1crypto-kitties~1nft~1aaa~1metadata-request'
      responses:
        200:
          description: ''
          headers: {}
  /nfts/collection/crypto-kitties/nft/{nft-id}/burn:
    put:
      tags:
      - Misc
      operationId: Burn (delete) a specify NFT.
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/~1nfts~1collection~1crypto-kitties~1nft~1aaa~1burn-request'
      responses:
        200:
          description: ''
          headers: {}
definitions:
  /nfts/mintrequest:
    title: /nfts/mintrequest
    example:
      base_req:
        from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
        memo: "Sent from Postman \U0001F680"
        chain_id: voter
        account_number: 0
        sequence: 1
        gas: 200000
        gas_adjustment: 1.2
        fees:
        - denom: token
          amount: 50
        simulate: false
      recipient: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
      denom: MyToken
      id: aaa
      tokenURI: http://localhost:8080
    type: object
    properties:
      base_req:
        $ref: '#/definitions/BaseReq'
      recipient:
        type: string
      denom:
        type: string
      id:
        type: string
      tokenURI:
        type: string
    required:
    - base_req
    - recipient
    - denom
    - id
    - tokenURI
  BaseReq:
    title: BaseReq
    example:
      from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
      memo: "Sent from Postman \U0001F680"
      chain_id: voter
      account_number: 0
      sequence: 1
      gas: 200000
      gas_adjustment: 1.2
      fees:
      - denom: token
        amount: 50
      simulate: false
    type: object
    properties:
      from:
        type: string
      memo:
        type: string
      chain_id:
        type: string
      account_number:
        type: string
      sequence:
        type: string
      gas:
        type: string
      gas_adjustment:
        type: string
      fees:
        type: array
        items:
          $ref: '#/definitions/Fee'
      simulate:
        type: boolean
    required:
    - from
    - memo
    - chain_id
    - account_number
    - sequence
    - gas
    - gas_adjustment
    - fees
    - simulate
  Fee:
    title: Fee
    example:
      denom: token
      amount: 50
    type: object
    properties:
      denom:
        type: string
      amount:
        type: string
    required:
    - denom
    - amount
  /nfts/transferrequest:
    title: /nfts/transferrequest
    example:
      base_req:
        from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
        memo: "Sent from Postman \U0001F680"
        chain_id: voter
        account_number: 0
        sequence: 1
        gas: 200000
        gas_adjustment: 1.2
        fees:
        - denom: token
          amount: 50
        simulate: false
      denom: MyToken
      id: aaa
      recipient: cosmos1atsc0j4w23derwmv98n72y28vdxsalp4zpcgz2
    type: object
    properties:
      base_req:
        $ref: '#/definitions/BaseReq'
      denom:
        type: string
      id:
        type: string
      recipient:
        type: string
    required:
    - base_req
    - denom
    - id
    - recipient
  /nfts/collection/crypto-kitties/nft/aaa/metadata-request:
    title: /nfts/collection/crypto-kitties/nft/aaa/metadata-request
    example:
      base_req:
        from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
        memo: "Sent from Postman \U0001F680"
        chain_id: voter
        account_number: 0
        sequence: 1
        gas: 200000
        gas_adjustment: 1.2
        fees:
        - denom: token
          amount: 50
        simulate: false
      denom: crypto-kitties
      id: aaa
      tokenURI: http://changeurl:8080
    type: object
    properties:
      base_req:
        $ref: '#/definitions/BaseReq'
      denom:
        type: string
      id:
        type: string
      tokenURI:
        type: string
    required:
    - base_req
    - denom
    - id
    - tokenURI
  /nfts/collection/crypto-kitties/nft/aaa/burn-request:
    title: /nfts/collection/crypto-kitties/nft/aaa/burn-request
    example:
      base_req:
        from: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
        memo: "Sent from Postman \U0001F680"
        chain_id: voter
        account_number: 0
        sequence: 1
        gas: 200000
        gas_adjustment: 1.2
        fees:
        - denom: token
          amount: 50
        simulate: false
      denom: crypto-kitties
      id: aaa
    type: object
    properties:
      base_req:
        $ref: '#/definitions/BaseReq'
      denom:
        type: string
      id:
        type: string
    required:
    - base_req
    - denom
    - id
tags:
- name: Misc
  description: ''
